# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function that triggers on an SNS topic publication when a new review is created to enrich the user's global stats

Resources:
    ProcessBuildGLobalStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-build-global-stats.default
            Runtime: nodejs10.x
            CodeUri: ./dist/process-build-global-stats
            Timeout: 40
            MemorySize: 384
            ReservedConcurrentExecutions: 5
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-build-global-stats
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: arn:aws:sqs:us-west-2:478062583808:ranked-review-published-queue
